import { APP_NAME } from "../constants";

export default function Home() {
  return (
    <>
      <section className='home-section'>
        <h2>Welcome to { APP_NAME }!</h2>
        <p>A platform to <a href='/explore'>explore</a> and <a href='/create'>share</a> tiny musical expressions.</p>

        <fieldset>
          <legend>What is bytebeat?</legend>
          <p>
            Bytebeat is a minimalist music format where sounds are generated by small programs
            that use arithmetic and bitwise operations to create unique algorithmic soundscapes.
          </p>

          <p><a href="/explore">Browse existing bytebeats</a> or <a href="/create">create your own</a>.</p>
        </fieldset>
      </section>
    </>
  );
}
